version: '3'

services:
  react-app:
    build:
      context: ./PharmacieLocationWeb
      
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app

  spring-boot-app:
    build:
      context: ./PharmacieAPI
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: pharmacieLocation
      MYSQL_ROOT_PASSWORD: root
